/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Answers whether the request carries the access token. */
        get: operations["get_session"];
        put?: never;
        /** Trades the access token for a session cookie. */
        post: operations["create_session"];
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Takes the gateway's own accounting records. A record this source already posted is
         *     counted as a duplicate, one this service cannot read is counted as rejected, and
         *     neither stops the rest of the batch.
         */
        post: operations["ingest_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Names an account for people. An absent, null or blank name clears it. */
        patch: operations["update_account"];
        trace?: never;
    };
    "/accounts/{account_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Folds an account into another of the same source: its events move to the target,
         *     and any record that later names its credential is charged to the target.
         */
        post: operations["merge_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_usage_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every event as it is committed, as Server-Sent Events of type `usage` whose id is
         *     the event id. Given `Last-Event-ID`, it first replays up to 500 stored events newer
         *     than that id, oldest first. A client that falls too far behind is disconnected and
         *     is expected to reconnect with `Last-Event-ID`.
         */
        get: operations["stream_usage_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usage_totals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usage_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Records a gateway sent that could not be read, newest first. Each is kept for 14
         *     days, with every field that could carry a credential removed.
         */
        get: operations["list_dead_letters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Without `history`, only the latest price of each provider, model, service tier,
         *     threshold and origin.
         */
        get: operations["list_prices"];
        put?: never;
        /**
         * Adds a manual price. A price is never edited: a change is a new row with a later
         *     `effective_from`, which defaults to now.
         */
        post: operations["create_price"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reads every configured LiteLLM map now. A map that cannot be read is named in
         *     `failed_sources` and the others still land.
         */
        post: operations["sync_prices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/reprice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prices every event in the range again with the prices in force when it happened.
         *     Both bounds are inclusive and optional.
         */
        post: operations["reprice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plans"];
        put?: never;
        post: operations["create_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_plan"];
        options?: never;
        head?: never;
        /** Absent fields keep their value; a null `period_end` makes the plan open ended. */
        patch: operations["update_plan"];
        trace?: never;
    };
    "/leverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every plan's latest billing periods, newest first, each with the list cost of the
         *     plan's account in it against the plan's price.
         */
        get: operations["leverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The last known state and quota of every CLIProxy credential, from the database only. */
        get: operations["list_quota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quota/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reads CLIProxy's credential list now, which reaches no provider, and answers every
         *     credential. 502 names each source that could not be read; the others are stored.
         */
        post: operations["sync_quota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quota/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asks each provider for its quota through CLIProxy, as the official management UI
         *     does, and answers every credential. Without `account_id` every hard-refreshable
         *     credential is refreshed. A credential whose provider fails records the reason in
         *     `hard_refresh_error` and counts in `failed`; it does not fail the request.
         */
        post: operations["refresh_quota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            account_id: string;
            source_id: string;
            source_name: string;
            provider: string;
            auth_kind: components["schemas"]["AuthKind"];
            label?: string;
            display_name?: string;
            /** @description The account this one was merged into. A merged account has no events of its own. */
            merged_into_account_id?: string;
            /** @description As the gateway last described the credential. */
            account_type?: string;
            plan?: string;
            first_seen_at: string;
            last_seen_at: string;
            /** Format: int64 */
            event_count: number;
        };
        /** AccountList */
        AccountList: {
            accounts: components["schemas"]["Account"][];
        };
        /** AccountSummary */
        AccountSummary: {
            account_id: string;
            source_id: string;
            source_name: string;
            provider: string;
            auth_kind: components["schemas"]["AuthKind"];
            label?: string;
            display_name?: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            display_name?: string;
        };
        /** @enum {string} */
        AuthKind: "oauth" | "api_key" | "unknown";
        /** @enum {string} */
        Bucket: "hour" | "day";
        /** CollectorState */
        CollectorState: {
            connected_since?: string;
            last_record_at?: string;
            /** Format: int64 */
            records_received: number;
            /** Format: int64 */
            consecutive_failures: number;
            last_error?: string;
            updated_at: string;
        };
        /**
         * Cooldown
         * @description A CLIProxy cooldown timer on the credential or on one of its models.
         */
        Cooldown: {
            scope: string;
            model_key?: string;
            reason: string;
            retry_at: string;
            /**
             * Format: int64
             * @description Seconds left when CLIProxy was last read.
             */
            remaining_seconds: number;
        };
        /** DeadLetter */
        DeadLetter: {
            dead_letter_id: string;
            source_id: string;
            received_at: string;
            error: string;
            /** @description The record as JSON text. */
            payload: string;
        };
        /** DeadLetterList */
        DeadLetterList: {
            dead_letters: components["schemas"]["DeadLetter"][];
        };
        /** Error */
        Error: {
            message: string;
        };
        /** EventPage */
        EventPage: {
            events: components["schemas"]["UsageEvent"][];
            next_before?: string;
        };
        /** @enum {string} */
        Grouping: "model" | "provider" | "account" | "harness" | "source";
        /** Health */
        Health: {
            status: string;
            version: string;
        };
        /** IngestInput */
        IngestInput: {
            records: unknown[];
        };
        /** IngestReport */
        IngestReport: {
            /** Format: int64 */
            accepted: number;
            /** Format: int64 */
            duplicates: number;
            /** Format: int64 */
            rejected: number;
        };
        /** Leverage */
        Leverage: {
            plans: components["schemas"]["PlanLeverage"][];
        };
        /**
         * LeveragePeriod
         * @description `period_end` is exclusive. `leverage` is list cost over the plan's price and absent for
         *     a free plan; `effective_usd_per_mtok` is absent when no token was used.
         */
        LeveragePeriod: {
            period_start: string;
            period_end: string;
            complete: boolean;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            list_cost_usd: number;
            /** Format: double */
            leverage?: number;
            /** Format: double */
            effective_usd_per_mtok?: number;
        };
        /** MergeInput */
        MergeInput: {
            into_account_id: string;
        };
        /** ModelPrice */
        ModelPrice: {
            price_id: string;
            provider?: string;
            model: string;
            service_tier?: string;
            /** Format: int64 */
            min_input_tokens: number;
            origin: components["schemas"]["PriceOrigin"];
            effective_from: string;
            /** Format: double */
            input_usd_per_mtok: number;
            /** Format: double */
            cached_input_usd_per_mtok: number;
            /** Format: double */
            cache_write_usd_per_mtok: number;
            /** Format: double */
            output_usd_per_mtok: number;
        };
        /** Plan */
        Plan: {
            plan_id: string;
            account: components["schemas"]["AccountSummary"];
            name: string;
            /** Format: double */
            monthly_usd: number;
            period_start: string;
            period_end?: string;
        };
        /**
         * PlanInput
         * @description Billing periods are calendar months from `period_start`'s day of month.
         */
        PlanInput: {
            account_id: string;
            name: string;
            /** Format: double */
            monthly_usd: number;
            period_start: string;
            period_end?: string;
        };
        /** PlanLeverage */
        PlanLeverage: {
            plan: components["schemas"]["Plan"];
            /** @description Newest first. */
            periods: components["schemas"]["LeveragePeriod"][];
        };
        /** PlanList */
        PlanList: {
            plans: components["schemas"]["Plan"][];
        };
        /** PlanUpdate */
        PlanUpdate: {
            account_id?: string;
            name?: string;
            /** Format: double */
            monthly_usd?: number;
            period_start?: string;
            period_end?: string | null;
        };
        /**
         * PriceInput
         * @description `provider` and `service_tier` absent mean any. `min_input_tokens` is the input size the
         *     price starts at, 0 by default.
         */
        PriceInput: {
            provider?: string;
            model: string;
            service_tier?: string;
            /** Format: int64 */
            min_input_tokens?: number;
            effective_from?: string;
            /** Format: double */
            input_usd_per_mtok: number;
            /** Format: double */
            cached_input_usd_per_mtok: number;
            /** Format: double */
            cache_write_usd_per_mtok: number;
            /** Format: double */
            output_usd_per_mtok: number;
        };
        /** PriceList */
        PriceList: {
            prices: components["schemas"]["ModelPrice"][];
        };
        /** @enum {string} */
        PriceOrigin: "manual" | "litellm_live" | "litellm_public";
        /** QuotaAccount */
        QuotaAccount: {
            account: components["schemas"]["AccountSummary"];
            status?: string;
            status_message?: string;
            disabled: boolean;
            unavailable: boolean;
            /**
             * @description CLIProxy's scheduling decision: the instant before which CLIProxy will not route
             *     requests to this credential. It is not the provider's quota reset time; that is
             *     `resets_at` on a window.
             */
            next_retry_after?: string;
            cooldowns: components["schemas"]["Cooldown"][];
            account_type?: string;
            plan?: string;
            /** @description When CLIProxy's credential list last described this credential. */
            soft_observed_at?: string;
            /** @description When a hard refresh last ran for this credential, successful or not. */
            hard_refreshed_at?: string;
            /** @description Why the last hard refresh failed; absent after a successful one. */
            hard_refresh_error?: string;
            /** @description Whether the provider has an adapter and the credential carries what it needs. */
            hard_refreshable: boolean;
            windows: components["schemas"]["QuotaWindow"][];
        };
        /** QuotaList */
        QuotaList: {
            accounts: components["schemas"]["QuotaAccount"][];
        };
        /** QuotaRefresh */
        QuotaRefresh: {
            /** Format: int64 */
            refreshed: number;
            /** Format: int64 */
            failed: number;
            accounts: components["schemas"]["QuotaAccount"][];
        };
        /** QuotaRefreshInput */
        QuotaRefreshInput: {
            account_id?: string;
        };
        /** QuotaSyncInput */
        QuotaSyncInput: {
            source_id?: string;
        };
        /**
         * QuotaWindow
         * @description One limit the provider reported at the last successful hard refresh.
         */
        QuotaWindow: {
            window_key: string;
            label: string;
            /**
             * Format: double
             * @description Share of the window used, 0 to 1, whatever unit the provider counts in.
             */
            used_fraction?: number;
            /** Format: double */
            used_value?: number;
            /** Format: double */
            limit_value?: number;
            /** @description What `used_value` and `limit_value` count. */
            unit?: string;
            /** Format: int64 */
            window_seconds?: number;
            /** @description When the provider said the window resets. */
            resets_at?: string;
            observed_at: string;
        };
        /** RepriceInput */
        RepriceInput: {
            from?: string;
            to?: string;
        };
        /** Repriced */
        Repriced: {
            /** Format: int64 */
            repriced: number;
        };
        /** SeriesBucket */
        SeriesBucket: {
            start: string;
            key: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            failures: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            list_cost_usd: number;
            /** Format: double */
            billed_cost_usd: number;
        };
        /** SeriesList */
        SeriesList: {
            buckets: components["schemas"]["SeriesBucket"][];
        };
        /** SessionInput */
        SessionInput: {
            token: string;
        };
        /** Source */
        Source: {
            source_id: string;
            /** @description The config file's name for the source. */
            key: string;
            name: string;
            kind: components["schemas"]["SourceKind"];
            base_url: string;
            enabled: boolean;
            created_at: string;
            last_event_at?: string;
            /** Format: int64 */
            event_count: number;
            collector?: components["schemas"]["CollectorState"];
        };
        /** @enum {string} */
        SourceKind: "cliproxy" | "litellm";
        /** SourceList */
        SourceList: {
            sources: components["schemas"]["Source"][];
        };
        /** SyncOutput */
        SyncOutput: {
            /** Format: int64 */
            inserted: number;
            /** Format: int64 */
            unchanged: number;
            /** @description The origin of every map that could not be read. */
            failed_sources: string[];
        };
        /** @enum {string} */
        TokenQuality: "complete" | "unclassified" | "inconsistent";
        /** Totals */
        Totals: {
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            failures: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            reasoning_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            cache_write_tokens: number;
            /** Format: int64 */
            unclassified_tokens: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            list_cost_usd: number;
            /** Format: double */
            billed_cost_usd: number;
            /**
             * Format: int64
             * @description Events no price has been found for yet, left out of `list_cost_usd`.
             */
            unpriced: number;
            /** Format: int64 */
            models: number;
            /** Format: int64 */
            accounts: number;
        };
        /** UsageEvent */
        UsageEvent: {
            event_id: string;
            source_id: string;
            upstream_id?: string;
            occurred_at: string;
            provider: string;
            model: string;
            model_alias?: string;
            endpoint: string;
            account: components["schemas"]["AccountSummary"];
            /** @description The client credential the request arrived with, masked. */
            caller?: string;
            harness?: string;
            user_agent?: string;
            session_id?: string;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            reasoning_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            cache_write_tokens: number;
            /** Format: int64 */
            unclassified_tokens: number;
            /** Format: int64 */
            total_tokens: number;
            token_quality?: components["schemas"]["TokenQuality"];
            /** Format: int64 */
            latency_ms?: number;
            /** Format: int64 */
            ttft_ms?: number;
            streamed: boolean;
            /** Format: int64 */
            status_code: number;
            failed: boolean;
            error_message?: string;
            service_tier?: string;
            reasoning_effort?: string;
            /** Format: double */
            list_cost_usd?: number;
            /** Format: double */
            billed_cost_usd?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Health"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["SessionInput"];
            };
        };
        responses: {
            204: {
                headers: {
                    "SET-COOKIE": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    "SET-COOKIE": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SourceList"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    get_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Source"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    ingest_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["IngestInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["IngestReport"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountList"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    update_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Account"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    merge_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["MergeInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Account"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_usage_events: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                source_id?: string;
                model?: string;
                account_id?: string;
                failed?: boolean;
                limit?: number;
                before?: string;
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["EventPage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    stream_usage_events: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["UsageEvent"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    usage_totals: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                source_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Totals"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    usage_series: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                bucket?: components["schemas"]["Bucket"];
                group_by?: components["schemas"]["Grouping"];
                source_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SeriesList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_dead_letters: {
        parameters: {
            query?: {
                source_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeadLetterList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_prices: {
        parameters: {
            query?: {
                model?: string;
                origin?: components["schemas"]["PriceOrigin"];
                history?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["PriceList"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    create_price: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["PriceInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ModelPrice"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    sync_prices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SyncOutput"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    reprice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["RepriceInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Repriced"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_plans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["PlanList"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    create_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["PlanInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Plan"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    update_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Plan"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    leverage: {
        parameters: {
            query?: {
                periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Leverage"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    list_quota: {
        parameters: {
            query?: {
                source_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuotaList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    sync_quota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["QuotaSyncInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuotaList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh_quota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; charset=utf-8": components["schemas"]["QuotaRefreshInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuotaRefresh"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Error"];
                };
            };
        };
    };
}
